### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kwshare** [hellokuls/cnnyzm#1]
`
Traceback (most recent call last):
  File "/Users/vm/Documents/workspace/First/_20200927/cnnyzm/process.py", line 80, in <module>
    x,y = next_batch(batch_count=1)
  File "/Users/vm/Documents/workspace/First/_20200927/cnnyzm/process.py", line 69, in next_batch
    image_a = image[text.index(text_a)]
IndexError: list index out of range
`

**Comment by hellokuls** [comment]
你没有成功读取到需要训练的图片

**Comment by didowithlove** [comment]
根据你验证码图片的长宽大小，修改一下getimg.py文件CAPTCHA_HEIGHT 和CAPTCHA_WIDTH参数的值
