### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Unbiseptium** [hellokuls/cnnyzm#10]
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    train()
  File "train.py", line 171, in train
    batch_x, batch_y = next_batch(64)
  File "C:\Users\11967\desktop\cnnyzm\process.py", line 61, in next_batch
    image_a = image[text.index(text_a)]
IndexError: list index out of range
？

**Comment by hellokuls** [comment]
一般是项目导入的时候出错了
